
server:
  port: 8082
spring:
  cloud:
    gateway:
      routes:
      - id: limit_route
        uri: http://127.0.0.1:8070/
        predicates:
        - After=2017-01-20T17:42:47.789-07:00[America/Denver]
        filters:
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@uriKeyResolver}'  # SPEL表达式去的对应的bean，配置限流方案
            redis-rate-limiter.replenishRate: 1  # 令牌桶平均速率
            redis-rate-limiter.burstCapacity: 3  # 令牌桶总容量
  application:
    name: gateway-limiter
  redis:
    host: 39.101.198.56
    port: 6379
    database: 13
    password: Xr20200101!


